export interface CallLogEntry {
  id: string;
  name: string;
  phone: string;
  type: "Inbound" | "Outbound";
  duration: string; // e.g., "05:23"
  dateTime: string; // ISO string or formatted string
  credits: number;
  response: "Interested" | "Not Interested" | "No Answer" | "Callback" | "Busy" | "Invalid";
  status: "Completed" | "Running" | "Failed";
  humanResponse: string; // Selected dropdown value
  recordingUrl: string;
  scriptUrl: string;
  aiClassification: string;
  agent: string;
  category: "Hot" | "Warm" | "Cold" | "Uncategorized";
}

export const mockCallLogs: CallLogEntry[] = [
  {
    id: "CL-1001",
    name: "Rahul Sharma",
    phone: "+91 98765 43210",
    type: "Outbound",
    duration: "04:15",
    dateTime: "2023-10-27T10:30:00Z",
    credits: 12,
    response: "Interested",
    status: "Completed",
    humanResponse: "Follow up needed",
    recordingUrl: "#",
    scriptUrl: "#",
    aiClassification: "High Intent Buyer",
    agent: "Sales AI Agent",
    category: "Hot",
  },
  {
    id: "CL-1002",
    name: "Ananya Iyer",
    phone: "+91 91234 56789",
    type: "Inbound",
    duration: "08:42",
    dateTime: "2023-10-27T11:15:00Z",
    credits: 24,
    response: "Callback",
    status: "Completed",
    humanResponse: "Meeting scheduled",
    recordingUrl: "#",
    scriptUrl: "#",
    aiClassification: "Needs Information",
    agent: "Support AI Agent",
    category: "Warm",
  },
  {
    id: "CL-1003",
    name: "Vikram Malhotra",
    phone: "+91 99887 76655",
    type: "Outbound",
    duration: "01:10",
    dateTime: "2023-10-27T14:20:00Z",
    credits: 4,
    response: "No Answer",
    status: "Completed",
    humanResponse: "Unreachable",
    recordingUrl: "#",
    scriptUrl: "#",
    aiClassification: "Unresponsive",
    agent: "Outreach Bot",
    category: "Cold",
  },
  {
    id: "CL-1004",
    name: "Karan Singh",
    phone: "+91 98712 34567",
    type: "Outbound",
    duration: "00:45",
    dateTime: "2023-10-27T15:05:00Z",
    credits: 2,
    response: "Not Interested",
    status: "Completed",
    humanResponse: "Do not call",
    recordingUrl: "#",
    scriptUrl: "#",
    aiClassification: "Opt-out",
    agent: "Sales AI Agent",
    category: "Cold",
  },
  {
    id: "CL-1005",
    name: "Marcus Holloway",
    phone: "+1 415 555 0198",
    type: "Inbound",
    duration: "12:30",
    dateTime: "2023-10-28T09:00:00Z",
    credits: 35,
    response: "Interested",
    status: "Completed",
    humanResponse: "Sent Proposal",
    recordingUrl: "#",
    scriptUrl: "#",
    aiClassification: "Ready to Buy",
    agent: "Premium Sales Agent",
    category: "Hot",
  },
  {
    id: "CL-1006",
    name: "Sarah Jenkins",
    phone: "+1 212 555 0123",
    type: "Outbound",
    duration: "00:00",
    dateTime: "2023-10-28T10:30:00Z",
    credits: 0,
    response: "Invalid",
    status: "Failed",
    humanResponse: "Wrong number",
    recordingUrl: "#",
    scriptUrl: "#",
    aiClassification: "Failed Connection",
    agent: "Outreach Bot",
    category: "Uncategorized",
  },
  {
    id: "CL-1007",
    name: "Robert Chen",
    phone: "+1 650 555 0155",
    type: "Outbound",
    duration: "02:20",
    dateTime: "2023-10-28T11:45:00Z",
    credits: 8,
    response: "Busy",
    status: "Running",
    humanResponse: "Try again later",
    recordingUrl: "#",
    scriptUrl: "#",
    aiClassification: "Pending Follow-up",
    agent: "Sales AI Agent",
    category: "Warm",
  },
  {
    id: "CL-1008",
    name: "Priya Patel",
    phone: "+91 90011 22334",
    type: "Inbound",
    duration: "06:15",
    dateTime: "2023-10-28T13:20:00Z",
    credits: 18,
    response: "Interested",
    status: "Completed",
    humanResponse: "Demo requested",
    recordingUrl: "#",
    scriptUrl: "#",
    aiClassification: "Product Inquiry",
    agent: "Support AI Agent",
    category: "Hot",
  },
  {
    id: "CL-1009",
    name: "David Smith",
    phone: "+44 20 7123 4567",
    type: "Outbound",
    duration: "03:50",
    dateTime: "2023-10-28T15:10:00Z",
    credits: 11,
    response: "Callback",
    status: "Completed",
    humanResponse: "Call back tomorrow",
    recordingUrl: "#",
    scriptUrl: "#",
    aiClassification: "Scheduling conflict",
    agent: "Sales AI Agent",
    category: "Warm",
  },
  {
    id: "CL-1010",
    name: "Elena Rodriguez",
    phone: "+34 91 123 45 67",
    type: "Outbound",
    duration: "01:30",
    dateTime: "2023-10-28T16:40:00Z",
    credits: 5,
    response: "Not Interested",
    status: "Completed",
    humanResponse: "Too expensive",
    recordingUrl: "#",
    scriptUrl: "#",
    aiClassification: "Price objection",
    agent: "Outreach Bot",
    category: "Cold",
  }
];

export const humanResponseOptions = [
  "Follow up needed",
  "Meeting scheduled",
  "Unreachable",
  "Do not call",
  "Sent Proposal",
  "Wrong number",
  "Try again later",
  "Demo requested",
  "Call back tomorrow",
  "Too expensive",
  "Other"
];
