"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/components/AuthProvider";
import DashboardShell from "@/components/DashboardShell";
import DataTable, { Column } from "@/components/shared/DataTable";
import Badge, { BadgeVariant } from "@/components/shared/Badge";
import DetailsDrawer from "@/components/shared/DetailsDrawer";
import DeleteConfirmationModal from "@/components/ui/DeleteConfirmationModal";
import { Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";

interface Lead {
  id: string;
  name: string;
  phone: string;
  category: string;
  datetime: string;
  score: number;
  latestResponse: string;
  transcript: Array<{ speaker: string; text: string }>;
  summary: string;
  notes: string;
}

const initialDummyLeads: Lead[] = [
  { id: "1", name: "Alice Johnson", phone: "+1 555-0101", category: "Hot", datetime: "2023-10-15 10:30", score: 95, latestResponse: "Send me the contract.", transcript: [{ speaker: "agent", text: "Ready to proceed?" }, { speaker: "customer", text: "Yes, send the contract." }], summary: "Customer is ready to buy.", notes: "High priority follow-up." },
  { id: "2", name: "Bob Smith", phone: "+1 555-0102", category: "Warm", datetime: "2023-10-15 11:00", score: 70, latestResponse: "I need more time to think.", transcript: [{ speaker: "agent", text: "Thoughts?" }, { speaker: "customer", text: "I need more time." }], summary: "Customer is interested but hesitating.", notes: "Follow up next week." },
  { id: "3", name: "Charlie Davis", phone: "+1 555-0103", category: "Cold", datetime: "2023-10-15 11:30", score: 30, latestResponse: "Not right now.", transcript: [{ speaker: "customer", text: "Not right now, maybe next year." }], summary: "Customer postponed decision.", notes: "Add to nurture sequence." },
  { id: "4", name: "Diana Evans", phone: "+1 555-0104", category: "Hot", datetime: "2023-10-15 12:15", score: 88, latestResponse: "Can we schedule a demo?", transcript: [{ speaker: "customer", text: "Can we schedule a demo?" }], summary: "Requested product demo.", notes: "Demo scheduled for Friday." },
  { id: "5", name: "Evan Wright", phone: "+1 555-0105", category: "Warm", datetime: "2023-10-15 13:00", score: 65, latestResponse: "Send pricing details.", transcript: [{ speaker: "customer", text: "Send pricing details." }], summary: "Requested pricing info.", notes: "Sent PDF via email." },
];

const getCategoryBadge = (category: string) => {
  const variantMap: Record<string, BadgeVariant> = {
    Hot: "error", // User requested Red for Hot
    Warm: "warning", // Orange
    Cold: "info", // Blue
  };
  return <Badge variant={variantMap[category] || "neutral"}>{category}</Badge>;
};

export default function LeadsPage() {
  const router = useRouter();
  const { isLoggedIn } = useAuth();
  
  const [leads, setLeads] = useState<Lead[]>(initialDummyLeads);
  const [selectedLead, setSelectedLead] = useState<Lead | null>(null);
  const [deleteConfirmationId, setDeleteConfirmationId] = useState<string | null>(null);

  useEffect(() => {
    if (!isLoggedIn) router.replace("/login");
  }, [isLoggedIn, router]);

  if (!isLoggedIn) return null;

  const handleDelete = (e: React.MouseEvent, id: string) => {
    e.stopPropagation();
    setDeleteConfirmationId(id);
  };

  const confirmDelete = () => {
    if (deleteConfirmationId) {
      setLeads(prev => prev.filter(l => l.id !== deleteConfirmationId));
      setDeleteConfirmationId(null);
    }
  };

  const columns: Column<Lead>[] = [
    { key: "name", label: "Name", sortable: true },
    { key: "phone", label: "Phone Number", sortable: true, render: (l) => <span className="font-mono text-xs">{l.phone}</span> },
    { key: "category", label: "Category", sortable: true, render: (l) => getCategoryBadge(l.category) },
    { key: "datetime", label: "Date & Time", sortable: true, render: (l) => <span className="text-xs">{l.datetime}</span> },
    { key: "actions", label: "Actions", render: (l) => (
      <div className="flex items-center gap-2">
        <Button
          variant="ghost"
          size="icon"
          onClick={(e) => handleDelete(e, l.id)}
          className="h-8 w-8 text-zinc-400 hover:text-red-600 dark:hover:text-red-400"
          title="Delete Lead"
        >
          <Trash2 className="h-4 w-4" />
        </Button>
      </div>
    )}
  ];

  return (
    <DashboardShell title="Leads">
      <div className="flex flex-col h-[calc(100vh-80px)] p-1 sm:p-4">
        <section className="flex flex-col flex-1 gap-4">
          <div>
            <h2 className="text-xl font-bold text-zinc-900 dark:text-white">Leads</h2>
            <p className="text-sm text-zinc-500 dark:text-zinc-400">
              Manage qualified leads generated by AI calls.
            </p>
          </div>
          <div className="flex-1 min-h-0">
            <DataTable 
              data={leads}
              columns={columns}
              searchableKeys={["name", "phone", "category"]}
              filters={[
                { key: "category", label: "Category", options: [{label: "Hot", value: "Hot"}, {label: "Warm", value: "Warm"}, {label: "Cold", value: "Cold"}] }
              ]}
              exportFileName="leads_export.xlsx"
              onRowClick={setSelectedLead}
            />
          </div>
        </section>
      </div>

      <DetailsDrawer
        isOpen={!!selectedLead}
        onClose={() => setSelectedLead(null)}
        title="Lead Details"
      >
        {selectedLead && (
          <div className="flex flex-col gap-6">
            <div className="rounded-xl border border-zinc-100 bg-zinc-50 p-4 dark:border-zinc-800 dark:bg-zinc-900/50">
              <h3 className="mb-4 text-sm font-bold uppercase tracking-wider text-zinc-500 dark:text-zinc-400">Profile</h3>
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div><span className="text-zinc-500">Name</span><p className="font-semibold dark:text-white">{selectedLead.name}</p></div>
                <div><span className="text-zinc-500">Phone</span><p className="font-semibold dark:text-white">{selectedLead.phone}</p></div>
                <div><span className="text-zinc-500">Category</span><p className="mt-1">{getCategoryBadge(selectedLead.category)}</p></div>
                <div>
                  <span className="text-zinc-500">Lead Score</span>
                  <div className="mt-1 flex items-center gap-2">
                    <div className="h-2 w-24 rounded-full bg-zinc-200 dark:bg-zinc-700">
                      <div className={`h-2 rounded-full ${selectedLead.score >= 80 ? 'bg-red-500' : selectedLead.score >= 50 ? 'bg-amber-500' : 'bg-blue-500'}`} style={{ width: `${selectedLead.score}%` }}></div>
                    </div>
                    <span className="font-bold">{selectedLead.score}</span>
                  </div>
                </div>
              </div>
            </div>

            <div className="rounded-xl border border-zinc-100 bg-zinc-50 p-4 dark:border-zinc-800 dark:bg-zinc-900/50">
              <h3 className="mb-4 text-sm font-bold uppercase tracking-wider text-zinc-500 dark:text-zinc-400">Call Summary</h3>
              <div className="mb-4">
                <span className="text-zinc-500 text-sm">Latest Response</span>
                <p className="font-medium dark:text-zinc-300 mt-1">"{selectedLead.latestResponse}"</p>
              </div>
              <div className="mb-4">
                <span className="text-zinc-500 text-sm">AI Summary</span>
                <p className="font-medium dark:text-zinc-300 mt-1">{selectedLead.summary}</p>
              </div>
              <div>
                <span className="text-zinc-500 text-sm">Notes</span>
                <p className="font-medium dark:text-zinc-300 mt-1">{selectedLead.notes}</p>
              </div>
            </div>

            <div className="rounded-xl border border-zinc-100 bg-zinc-50 p-4 dark:border-zinc-800 dark:bg-zinc-900/50">
              <h3 className="mb-4 text-sm font-bold uppercase tracking-wider text-zinc-500 dark:text-zinc-400">Transcript</h3>
              <div className="flex flex-col gap-3">
                {selectedLead.transcript.map((msg, i) => (
                  <div key={i} className={`flex ${msg.speaker === "agent" ? "justify-end" : "justify-start"}`}>
                    <div className={`max-w-[80%] rounded-2xl px-4 py-2 text-sm ${msg.speaker === "agent" ? "bg-violet-600 text-white" : "bg-zinc-200 text-zinc-900 dark:bg-zinc-700 dark:text-zinc-100"}`}>
                      {msg.text}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </DetailsDrawer>

      <DeleteConfirmationModal
        isOpen={!!deleteConfirmationId}
        title="Delete Lead?"
        description="Are you sure you want to delete this lead? This action cannot be undone."
        onConfirm={confirmDelete}
        onCancel={() => setDeleteConfirmationId(null)}
      />
    </DashboardShell>
  );
}
